# Generated by Django 4.1.5 on 2023-01-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paperless_mail", "0016_mailrule_consumption_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailrule",
            name="filter_to",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="filter to"
            ),
        ),
    ]
