#!/usr/bin/with-contenv bash
# shellcheck shell=bash

paperless_src_dir="/usr/src/paperless/src"
index_version=3
data_dir="${PAPERLESS_DATA_DIR:-/usr/src/paperless/data}"
index_version_file="${data_dir}/.index_version"

if [[ (! -f "${index_version_file}") || $(<"${index_version_file}") != "$index_version" ]]; then
	echo "Search index out of date. Updating..."
	cd "${paperless_src_dir}"
	ls -ahl
	s6-setuidgid paperless python --version
	s6-setuidgid paperless python3 manage.py document_index reindex --no-progress-bar
	echo "Writing to file"
	echo ${index_version} | s6-setuidgid paperless  tee "${index_version_file}" >/dev/null
fi
