#!/command/with-contenv bash
# shellcheck shell=bash

index_version=3
index_version_file=${DATA_DIR}/.index_version

if [[ (! -f "${index_version_file}") || $(<"${index_version_file}") != "$index_version" ]]; then
	echo "Search index out of date. Updating..."
	s6-setuidgid paperless python3 manage.py document_index reindex --no-progress-bar
	s6-setuidgid paperless echo ${index_version} | tee "${index_version_file}" >/dev/null
fi
