#!/usr/bin/with-contenv bash
# shellcheck shell=bash

paperless_src_dir="/usr/src/paperless/src"

if [[ -n "${PAPERLESS_ADMIN_USER}" ]]; then
	cd "${paperless_src_dir}"
	s6-setuidgid paperless python3 manage.py manage_superuser
fi
