#!/command/with-contenv bash
# shellcheck shell=bash

echo "Checking if we should start flower..."

if [[ -n  "${PAPERLESS_ENABLE_FLOWER}" ]]; then
	# Small delay to allow celery to be up first
	echo "Starting flower in 5s"
	sleep 5
	s6-svc -U /run/s6/services/svc-flower
else
	echo "Not starting flower"
fi
