#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cd ${PAPERLESS_SRC_DIR}

s6-setuidgid paperless /usr/local/bin/celery --app paperless flower --conf=${PAPERLESS_SRC_DIR}/paperless/flowerconfig.py
