# Generated by Django 4.1.5 on 2023-02-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1030_alter_paperlesstask_task_file_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="storage_type",
        ),
    ]
