#!/command/with-contenv bash
# shellcheck shell=bash

paperless_src_dir="/usr/src/paperless/src"

# Explicitly run the Django system checks
echo "Running Django checks"

cd "${paperless_src_dir}"
s6-setuidgid paperless python3 manage.py check
